### ISSUE TITLE
Version 0.1.2 has not been published to the npm registry

### ISSUE THREAD

**Issue by suprememoocow** [SBoudrias/class-extend#3]
Currently (as of 12 Oct 2015), version 0.1.2 has not been published to the npm repository.

I'm keen to use this library in a library I'm writing, but don't want a dependency on the entire lodash library as it would add a lot of unnecessary code (it's intended to be used in the browser).

Any chance you could publish 0.1.2?

**Comment by SBoudrias** [comment]
Woops, sorry about that. It's published now.
